# Numpy

In [1]:
import numpy as np
print(np.__version__) 

2.0.2


In [2]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

# Built-in functions
zeros = np.zeros((3, 4))      
ones = np.ones((2, 3))         
empty = np.empty((2, 2))       
range_arr = np.arange(0, 10, 2)  
linspace = np.linspace(0, 1, 5)  
identity = np.eye(3)           
random_arr = np.random.rand(3, 3)  

In [23]:
arr1

array([1, 2, 3, 4, 5])

In [3]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [25]:
empty

array([[5.21594984e-319, 0.00000000e+000],
       [6.64444169e-310, 6.64444168e-310]])

In [26]:
linspace

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [27]:
random_arr

array([[0.04731659, 0.64575685, 0.27708135],
       [0.13840984, 0.25384525, 0.32126627],
       [0.78541726, 0.31120542, 0.79865057]])

In [5]:
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
#Array Attributes
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(f"Shape: {arr.shape}")      
print(f"Dimensions: {arr.ndim}")  
print(f"Size: {arr.size}")         
print(f"Data type: {arr.dtype}")   
print(f"Item size: {arr.itemsize} bytes")  
print(f"Total bytes: {arr.nbytes}") 

Shape: (2, 4)
Dimensions: 2
Size: 8
Data type: int64
Item size: 8 bytes
Total bytes: 64


In [7]:
#Array Indexing and Slicing
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Basic indexing
print(arr[0, 1])        
print(arr[1])          

# Slicing
print(arr[:, 1])      
print(arr[0:2, 1:3])   
print(arr[::-1])       

# Boolean indexing
print(arr[arr > 5])     

2
[5 6 7 8]
[ 2  6 10]
[[2 3]
 [6 7]]
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
[ 6  7  8  9 10 11 12]


In [8]:
#Array Operations
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

# Arithmetic operations
print(a + b)      
print(a * b)     
print(a ** 2)     
print(np.sqrt(a)) 

# Universal functions 
print(np.sin(a))  
print(np.exp(a))
print(np.log(a))  

[ 6  8 10 12]
[ 5 12 21 32]
[ 1  4  9 16]
[1.         1.41421356 1.73205081 2.        ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436]


In [9]:
#Broadcasting
# NumPy can perform operations on arrays of different shapes
arr = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 10

print(arr + scalar)  

row = np.array([1, 2, 3])
print(arr + row)  


[[11 12 13]
 [14 15 16]]
[[2 4 6]
 [5 7 9]]


In [10]:
#Aggregation Functions
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(f"Sum: {np.sum(arr)}")              
print(f"Mean: {np.mean(arr)}")            
print(f"Std deviation: {np.std(arr)}")     
print(f"Min: {np.min(arr)}")               
print(f"Max: {np.max(arr)}")               

# Axis-wise operations
print(f"Sum across rows: {np.sum(arr, axis=0)}") 
print(f"Sum across columns: {np.sum(arr, axis=1)}") 

# Cumulative operations
print(f"Cumulative sum: {np.cumsum(arr)}")

Sum: 45
Mean: 5.0
Std deviation: 2.581988897471611
Min: 1
Max: 9
Sum across rows: [12 15 18]
Sum across columns: [ 6 15 24]
Cumulative sum: [ 1  3  6 10 15 21 28 36 45]


In [28]:
#Reshaping and Manipulation
arr = np.arange(12)
print(arr)
# Reshape
reshaped = arr.reshape(3, 4)
print(reshaped)

# Flatten
flattened = reshaped.flatten() 
raveled = reshaped.ravel()       

# Stacking
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.vstack((a, b)))  
print(np.hstack((a, b)))  

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [12]:
#Linear Algebra Operations
# Matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A, B))  
print(A @ B)         


print(np.linalg.inv(A))      
print(np.linalg.det(A))     
print(np.linalg.eig(A))      


# Solve: 3x + y = 9, x + 2y = 8
coefficients = np.array([[3, 1], [1, 2]])
constants = np.array([9, 8])
solution = np.linalg.solve(coefficients, constants)
print(solution)  # [2, 3]

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004
EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))
[2. 3.]


In [9]:
#Practical Examples
#Data Normalization
def normalize_data(data):
    """Normalize data to have mean 0 and std 1"""
    return (data - np.mean(data)) / np.std(data)

data = np.random.randn(1000) * 10 + 5  # Generate random data of 1000 data points
print(data)
print("======================================================")
normalized = normalize_data(data)
print(f"After normalization - Mean: {np.mean(normalized):.2f}, Std: {np.std(normalized):.2f}")


[ 1.76651974e+00 -6.15626203e+00  3.13138676e+01  8.05692118e+00
  4.57911532e+00 -1.56965276e+00  6.31642401e+00 -1.90819915e+00
 -1.94899779e+01  1.56517998e+01  1.15536298e+01  9.30481290e+00
 -9.61629159e+00  1.05767352e+01 -7.66368547e-01  1.00570255e+01
  1.29922868e+00 -3.72849717e+00  3.93701011e+00  3.83612053e+00
 -7.97690519e+00 -5.52983241e+00  3.28063898e+00  4.39379291e+00
 -4.10840680e-01  2.67430008e+00 -1.47536289e+01  6.90239336e-01
 -1.98398236e+00 -1.40193581e+01  1.26423151e+01 -4.92087513e+00
 -1.59846138e+01 -6.31147369e+00 -4.77983081e+00  4.50581799e+00
  1.75661999e+01  1.76442318e+00 -1.83513648e+00  1.18946957e+00
  3.28667053e+00 -1.11779544e+01  2.87794926e+01 -2.07615422e-01
  8.99851324e+00  6.94233772e+00 -9.49802859e+00  9.89114300e+00
 -8.86184461e+00  1.48492800e+01  1.59422565e+00  2.30991691e+01
  1.72865623e+00 -5.69513430e+00  6.84845759e+00  2.84464529e-01
  2.32609021e+01  3.48379637e+01 -8.76532003e+00  2.13082978e-01
  9.55765441e-01  8.20970

In [ ]:
#Basic Exception Handling Syntax

try:
    
    risky_operation()
except ExceptionType:

    handle_error()

In [17]:
# Example 1: Handling division by zero
try:
    numerator = 10
    denominator = 0
    result = numerator / denominator
    print(f"Result: {result}")
except ZeroDivisionError:
    print("Error: Cannot divide by zero!")


Error: Cannot divide by zero!


In [21]:
# Handle different types of exceptions
try:
    num = int(input("Enter a number: "))
    result = 100 / num
    print(f"100 divided by {num} is {result}")

    my_list = [1, 2, 3]
    print(my_list[num])

except ZeroDivisionError:
    print("You cannot divide by zero!")
except ValueError:
    print("Please enter a valid number!")
except IndexError:
    print("Index out of range!")

Enter a number: 1.5
Please enter a valid number!


In [22]:
#Catching Multiple Exceptions in One Block
try:
    num = int(input("Enter a number: "))
    result = 100 / num
except (ValueError, ZeroDivisionError) as e:
    print(f"An error occurred: {e}")
    print(f"Error type: {type(e).__name__}")

Enter a number: 1.5
An error occurred: invalid literal for int() with base 10: '1.5'
Error type: ValueError


In [6]:
#The Complete Try-Except-Else-Finally Structure
#Full Exception Handling Structure

try:
   
    file = open("data.txt", "r")
    content = file.read()
    number = int(content)
    result = 100 / number

except FileNotFoundError:
    print("File not found!")

except ValueError:
    print("File doesn't contain a valid number!")

except ZeroDivisionError:
    print("Number in file is zero!")

else:
    
    print(f"Success! Result: {result}")

finally:
   
    print("Cleaning up...")
    if 'file' in locals() and not file.closed:
        file.close()
        print("File closed.")

File not found!
Cleaning up...


    ┌─────────────────┐
    │     try         │
    │  (risky code)   │
    └────────┬────────┘
             │
    ┌────────┴────────┐
    │  Exception?     │
    └────────┬────────┘
             │
    ┌────────┴────────┐    ┌─────────────────┐
    │      Yes        │───▶│     except      │
    └─────────────────┘    │  (handle error) │
                           └────────┬────────┘
                                    │
    ┌─────────────────┐    ┌────────┴────────┐
    │       No        │───▶│      else       │
    └─────────────────┘    │ (if no error)   │
                           └────────┬────────┘
                                    │
                           ┌────────┴────────┐
                           │     finally     │
                           │  (always runs)  │
                           └─────────────────┘